# -*- mode: makefile-gmake; -*-
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2024-2026 Urutau-Ltd <softwarelibre@urutau-ltd.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

TAG := sl.urutau-ltd.org/urutau-ltd/urutau-ltd:latest

image: ## Make a builder podman image for this site
	@echo "==> [LUME/PODMAN]: Building podman image..."
	podman build -t $(TAG) .
	@echo "==> [LUME/PODMAN]: Finished building podman image!"

compose-up:
	podman compose up -d

compose-down:
	podman compose down

compose-restart: compose-up compose-down

oci-run: ## Test the built image locally by running it
	@echo "==> [LUME/PODMAN-RUN]: Running site image locally on port 8000..."
	podman run --rm -p 8000:8000 -e URUTAU_PORT=8000 $(TAG)
	@echo "==> [LUME/PODMAN-RUN]: Container stopped."

push-image: ## Push OCI image to the container registry
	podman push --tls-verify=false $(TAG)
