/**
 * Standalone, no deps MCP server using a JSON RPC-like response system. Made
 * in absolutely lazy mode. Audited by the robot to test it does work well.
 */
import { walk } from "@std/fs/walk";
import { escape } from "@std/regexp/escape";

// Wrong duplication is better than wrong abstraction, however I do not want
// to bloat this script while these two should be the same values.
import { buildSkipPattern, SKIPPED_DIRS } from "$urutau/lib/debt_harvester.ts";

type SymbolKind =
    | "function"
    | "class"
    | "interface"
    | "type"
    | "const"
    | "enum"
    | "reexport"
    | "ref";

interface Hit {
    file: string;
    line: number;
    kind: SymbolKind;
    text: string;
}

const ENCODER: TextEncoder = new TextEncoder();
const DECODER: TextDecoder = new TextDecoder();

const SOURCE_EXTENSIONS: string[] = [
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
];

const SOURCE_DIRS: readonly string[] = ["lib", "src", "scripts", "tests"];

const TOOLS = [
    {
        name: "where_is",
        description:
            `Find every exported definition matching a symbol name across the 
            project TypeScript TSX source. Returns file, line, kind, and
            declaration text.`,
        inputSchema: {
            type: "object",
            properties: {
                name: {
                    type: "string",
                    description: "Symbol name to search for",
                },
            },
            required: ["name"],
        },
    },
    {
        name: "outline",
        description:
            `List all exported symbols from one source file with declaration 
            kind and line number. Accepts a relative path, full path, or
            basename.`,
        inputSchema: {
            type: "object",
            properties: {
                module: {
                    type: "string",
                    description: "Module path or name e.g. lib/debt_harvester",
                },
            },
            required: ["module"],
        },
    },
    {
        name: "references_to",
        description:
            `Find every line where a symbol name appears as a word-boundary 
            match across project source files. Skips comment-only lines.
            Text-based not AST.`,
        inputSchema: {
            type: "object",
            properties: {
                name: {
                    type: "string",
                    description: "Symbol name to search for",
                },
            },
            required: ["name"],
        },
    },
];

/**
 * @description - This RegExp was generated by the robot. Tested it against this
 * codebase and it works fine. Might not for other codebases and I'm too lazy
 * to check for you.
 */
const EXPORT_RE: RegExp =
    /^\s*export\s+(?:(?:default\s+)?(?:async\s+)?(?:function|class)|const|interface|type|enum)\s+(\w+)/;

const REEXPORT_RE: RegExp = /^\s*export\s*\{[^}]*\b(\w+)\b[^}]*\}/g;

const skipPatterns: RegExp[] = SKIPPED_DIRS.map(buildSkipPattern);

const sourceFiles = async (): Promise<string[]> => {
    const results: string[] = [];
    for (const dir of SOURCE_DIRS) {
        try {
            for await (
                const entry of walk(dir, {
                    skip: skipPatterns,
                    includeDirs: false,
                    exts: SOURCE_EXTENSIONS,
                })
            ) {
                results.push(entry.path);
            }
        } catch {
            /* Directory may not exist, do nothing */
        }
    }
    return results;
};

const classifyKind = (line: string): SymbolKind => {
    if (line.includes("interface")) return "interface";
    if (line.includes("function") || line.includes("async")) return "function";
    if (line.includes("class")) return "class";
    if (line.includes("type")) return "type";
    if (line.includes("enum")) return "enum";
    return "const";
};

const whereIs = async (name: string): Promise<Hit[]> => {
    const results: Hit[] = [];

    for (const file of await sourceFiles()) {
        let content: string;
        try {
            content = Deno.readTextFileSync(file);
        } catch {
            continue;
        }
        const lines: string[] = content.split("\n");
        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            if (/^\s*\/\//.test(line)) continue;
            const m = line.match(EXPORT_RE);
            if (m && m[1] === name) {
                results.push({
                    file,
                    line: i + 1,
                    kind: classifyKind(line),
                    text: line.trim(),
                });
                continue;
            }
            for (const rm of line.matchAll(REEXPORT_RE)) {
                if (rm[1] === name) {
                    results.push({
                        file,
                        line: i + 1,
                        kind: "reexport",
                        text: line.trim(),
                    });
                }
            }
        }
    }
    return results;
};

const resolveModule = async (query: string): Promise<string | null> => {
    const norm: string = query.trim().replace(/\\/g, "/");
    for (const ext of ["", ".ts", ".tsx", ".js", ".jsx"]) {
        const candidate: string = norm + ext;
        try {
            Deno.statSync(candidate);
            return candidate;
        } catch {
            /* do nothing if not found */
        }
    }
    for (const file of await sourceFiles()) {
        const base: string = file.slice(file.lastIndexOf("/") + 1);
        const noExt = base.replace(/\.[^.]+$/, "");
        if (noExt === norm) return file;
    }
    return null;
};

const outline = async (module: string): Promise<Hit[]> => {
    const resolved: string | null = await resolveModule(module);
    if (!resolved) return [];
    let content: string;
    try {
        content = Deno.readTextFileSync(resolved);
    } catch {
        return [];
    }
    const results: Hit[] = [];
    const lines: string[] = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
        const line: string = lines[i];
        if (/^\s*\/\//.test(line)) continue;
        const m: RegExpMatchArray | null = line.match(EXPORT_RE);
        if (m) {
            results.push({
                file: resolved,
                line: i + 1,
                kind: classifyKind(line),
                text: line.trim(),
            });
        }
        for (const _ of line.matchAll(REEXPORT_RE)) {
            results.push({
                file: resolved,
                line: i + 1,
                kind: "reexport",
                text: line.trim(),
            });
        }
    }
    return results;
};

const referencesTo = async (name: string): Promise<Hit[]> => {
    const pattern: RegExp = new RegExp("\\b" + escape(name) + "\\b");
    const results: Hit[] = [];
    for (const file of await sourceFiles()) {
        let content: string;
        try {
            content = Deno.readTextFileSync(file);
        } catch {
            continue;
        }
        const lines: string[] = content.split("\n");
        for (let i = 0; i < lines.length; i++) {
            const line: string = lines[i];
            if (/^\s*\/\//.test(line)) continue;
            if (/^\s*\*/.test(line)) continue;
            if (/^\s*\/\*/.test(line)) continue;
            if (pattern.test(line)) {
                results.push({
                    file,
                    line: i + 1,
                    kind: "ref",
                    text: line.trim(),
                });
            }
        }
    }
    return results;
};

const formatHits = (hits: Hit[], label: string): string => {
    if (hits.length === 0) return label + ": none";
    const lines: string[] = [label + ":"];
    for (const h of hits) {
        lines.push(
            "  " + h.file + ":" + h.line + "  [" + h.kind + "] " + h.text,
        );
    }
    return lines.join("\n");
};

const processRequest = async (
    req: Record<string, unknown>,
): Promise<Record<string, unknown> | null> => {
    const id = req.id as number | string | undefined;
    const method = req.method as string;

    if (method === "initialize") {
        return {
            jsonrpc: "2.0",
            id,
            result: {
                protocolVersion: "2024-11-05",
                capabilities: { tools: {} },
                serverInfo: {
                    name: "urutau-codebase-search",
                    version: "1.0.0",
                },
            },
        };
    }

    if (method === "tools/list") {
        return {
            jsonrpc: "2.0",
            id,
            result: { tools: TOOLS },
        };
    }

    if (method === "tools/call") {
        const params: Record<string, unknown> = req.params as Record<
            string,
            unknown
        >;

        const toolName: string = params.name as string;
        const args: Record<string, string> = (params.arguments || {}) as Record<
            string,
            string
        >;

        let text: string;
        if (toolName === "where_is") {
            if (!args.name?.trim()) {
                console.error(
                    `[MCP] Invalid args for where_is: name missing or empty`,
                );
                text = "Error: name parameter required and non-empty";
            } else {
                const hits = await whereIs(args.name);
                text = formatHits(
                    hits,
                    hits.length + " definition(s) of " +
                        JSON.stringify(args.name),
                );
            }
        } else if (toolName === "outline") {
            if (!args.module?.trim()) {
                console.error(
                    `[MCP] Invalid args for outline: module missing or empty`,
                );
                text = "Error: module parameter required and non-empty";
            } else {
                const hits = await outline(args.module);
                if (hits.length === 0) {
                    text = "No module matching " +
                        JSON.stringify(args.module) +
                        " or no exports found";
                } else {
                    text = formatHits(
                        hits,
                        hits.length + " export(s) from " + hits[0].file,
                    );
                }
            }
        } else if (toolName === "references_to") {
            if (!args.name?.trim()) {
                console.error(
                    `[MCP] Invalid args for references_to: name missing or empty`,
                );
                text = "Error: name parameter required and non-empty";
            } else {
                const hits = await referencesTo(args.name);
                text = formatHits(
                    hits,
                    hits.length + " reference(s) to " +
                        JSON.stringify(args.name),
                );
            }
        } else {
            return {
                jsonrpc: "2.0",
                id,
                error: {
                    code: -32601,
                    message: "Unknown tool: " + toolName,
                },
            };
        }

        return {
            jsonrpc: "2.0",
            id,
            result: { content: [{ type: "text", text }] },
        };
    }

    if (method && !method.startsWith("notifications/")) {
        return {
            jsonrpc: "2.0",
            id,
            error: {
                code: -32601,
                message: "Method not found: " + method,
            },
        };
    }

    return null;
};

const main = async (): Promise<void> => {
    Deno.addSignalListener("SIGTERM", () => Deno.exit(0));

    let buffer: string = "";
    for await (const chunk of Deno.stdin.readable) {
        buffer += DECODER.decode(chunk);
        if (buffer.length > 1_000_000) {
            console.error("[MCP] Buffer exceeded 1MB, closing");
            Deno.exit(1);
        }
        let nl: number;

        while ((nl = buffer.indexOf("\n")) !== -1) {
            const line: string = buffer.slice(0, nl).trim();
            buffer = buffer.slice(nl + 1);

            if (!line) continue;

            try {
                const req = JSON.parse(line);
                const res: Record<string, unknown> | null =
                    await processRequest(req);

                if (res) {
                    await Deno.stdout.write(
                        ENCODER.encode(JSON.stringify(res) + "\n"),
                    );
                }
            } catch {
                const err = {
                    jsonrpc: "2.0",
                    id: null,
                    error: { code: -32700, message: "Parse error" },
                };
                await Deno.stdout.write(
                    ENCODER.encode(JSON.stringify(err) + "\n"),
                );
            }
        }
    }
};

main();
